// Cosmic Courier - Ship & Mission Catalog
import { Ship, Mission, PlayerProfile, Contract } from '../types/game';

// Helper to generate jagged asteroid vertices
export function generateAsteroidVertices(radius: number, points: number = 8): { x: number; y: number }[] {
  const vertices = [];
  for (let i = 0; i < points; i++) {
    const angle = (i / points) * Math.PI * 2;
    // Vary radius by 15-35% for rocky, craggy asteroid contours
    const r = radius * (0.8 + Math.sin(i * 3.7 + radius) * 0.25);
    vertices.push({
      x: Math.cos(angle) * r,
      y: Math.sin(angle) * r,
    });
  }
  return vertices;
}

export const SHIPS: Ship[] = [
  {
    id: 'star_sparrow',
    name: 'Star Sparrow',
    tagline: 'Standard Light Shuttle',
    description: 'The standard workhorse of the Courier Guild. Balanced handling, forgiving inertia, and dependable thrusters.',
    cost: 0,
    unlockedByDefault: true,
    color: '#00f0ff',
    accentColor: '#38bdf8',
    engineColor: '#0ea5e9',
    stats: {
      speed: 5.5,
      acceleration: 0.16,
      turnRate: 0.065,
      boostPower: 1.8,
      boostMaxDuration: 3.5,
      collisionResistance: 0.2, // 20% impact mitigation
      fuelCapacity: 100,        // Standard 100L propellant tank
      fuelBurnRate: 1.0,        // Balanced burn rate
      handlingName: 'Balanced Agile',
    },
  },
  {
    id: 'nebula_swift',
    name: 'Nebula Swift',
    tagline: 'Hyper-Agile Interceptor',
    description: 'Ultra-light chassis built for pinpoint maneuvering through dense obstacle clusters and narrow gaps.',
    cost: 400,
    unlockedByDefault: false,
    color: '#39ff14', // Neon Lime
    accentColor: '#10b981',
    engineColor: '#22c55e',
    stats: {
      speed: 6.2,
      acceleration: 0.21,
      turnRate: 0.088,
      boostPower: 1.9,
      boostMaxDuration: 4.0,
      collisionResistance: 0.15,
      fuelCapacity: 85,         // Compact tank for weight reduction
      fuelBurnRate: 1.15,       // Burns hotter for high acceleration
      handlingName: 'Ultra High Agility',
    },
  },
  {
    id: 'titan_hauler',
    name: 'Titan Hauler',
    tagline: 'Heavy Armored Transport',
    description: 'Reinforced kinetic plating and package inertia dampeners minimize cargo damage on asteroid impacts.',
    cost: 750,
    unlockedByDefault: false,
    color: '#f59e0b', // Neon Amber
    accentColor: '#fbbf24',
    engineColor: '#d97706',
    stats: {
      speed: 4.8,
      acceleration: 0.12,
      turnRate: 0.05,
      boostPower: 1.6,
      boostMaxDuration: 5.0,
      collisionResistance: 0.55, // 55% damage reduction on collisions!
      fuelCapacity: 150,        // High-capacity dual industrial fuel tanks
      fuelBurnRate: 0.85,       // Economical heavy burn cycle
      handlingName: 'Heavy Plated',
    },
  },
  {
    id: 'solar_dart',
    name: 'Solar Dart',
    tagline: 'High-Velocity Speedrunner',
    description: 'Twin supercharged ion drives deliver blistering top speeds and instantaneous boost acceleration.',
    cost: 1200,
    unlockedByDefault: false,
    color: '#ec4899', // Neon Pink / Magenta
    accentColor: '#f43f5e',
    engineColor: '#e11d48',
    stats: {
      speed: 7.6,
      acceleration: 0.25,
      turnRate: 0.062,
      boostPower: 2.3,
      boostMaxDuration: 4.5,
      collisionResistance: 0.25,
      fuelCapacity: 90,         // High-velocity racing propellant cell
      fuelBurnRate: 1.35,       // High fuel burn rate under full thrust
      handlingName: 'Supersonic Boost',
    },
  },
  {
    id: 'quantum_phantom',
    name: 'Quantum Phantom',
    tagline: 'Experimental Stealth Prototype',
    description: 'Equipped with grav-dampening micro-thrusters, magnetic cargo stabilization, and cutting-edge propulsion.',
    cost: 2000,
    unlockedByDefault: false,
    color: '#a855f7', // Neon Purple
    accentColor: '#c084fc',
    engineColor: '#9333ea',
    stats: {
      speed: 7.0,
      acceleration: 0.22,
      turnRate: 0.078,
      boostPower: 2.1,
      boostMaxDuration: 6.0,
      collisionResistance: 0.4,
      fuelCapacity: 120,        // Quantum-densified fuel storage
      fuelBurnRate: 0.9,        // High-efficiency micro-thrusters
      handlingName: 'Grav-Dampened Elite',
    },
  },
];

export const CAMPAIGN_MISSIONS: Mission[] = [
  // 1. ROOKIE RUN
  {
    id: 'mission_1',
    codeName: 'SEC-01',
    title: 'Lunar Outpost Hop',
    sector: 'Cislunar Transit Corridor',
    difficulty: 'rookie',
    description: 'A beginner delivery run from Station Alpha to Outpost Luna. Master ship handling, test the retro thrusters, and practice your precision landing.',
    cargoName: 'Medical Cryo-Vials',
    cargoDescription: 'Temperature-sensitive medical serum. Moderate fragility.',
    timeLimit: 55,
    rewardCredits: 150,
    baseScore: 1000,
    unlockRequirement: { type: 'default' },
    worldWidth: 2600,
    worldHeight: 1400,
    startPos: { x: 250, y: 700, angle: 0 },
    landingPad: {
      x: 2350,
      y: 700,
      width: 130,
      height: 130,
      targetAngle: 0,
      safeSpeedMax: 2.2,
    },
    asteroids: [
      {
        id: 'ast_1_1',
        type: 'asteroid_static',
        x: 650,
        y: 600,
        radius: 45,
        rotation: 0.4,
        rotationSpeed: 0.005,
        vertices: generateAsteroidVertices(45),
      },
      {
        id: 'ast_1_2',
        type: 'asteroid_static',
        x: 950,
        y: 820,
        radius: 55,
        rotation: 1.2,
        rotationSpeed: -0.004,
        vertices: generateAsteroidVertices(55),
      },
      {
        id: 'ast_1_3',
        type: 'asteroid_static',
        x: 1300,
        y: 520,
        radius: 65,
        rotation: 2.1,
        rotationSpeed: 0.006,
        vertices: generateAsteroidVertices(65),
      },
      {
        id: 'ast_1_4',
        type: 'asteroid_static',
        x: 1650,
        y: 780,
        radius: 50,
        rotation: 0.8,
        rotationSpeed: -0.005,
        vertices: generateAsteroidVertices(50),
      },
      {
        id: 'ast_1_5',
        type: 'asteroid_static',
        x: 1950,
        y: 620,
        radius: 40,
        rotation: 1.5,
        rotationSpeed: 0.003,
        vertices: generateAsteroidVertices(40),
      },
    ],
    gravityWells: [],
    lasers: [],
    bonusRings: [
      { id: 'ring_1_1', x: 800, y: 700, radius: 42, rotation: 0, collected: false, scoreValue: 250, stabilityBonus: 5 },
      { id: 'ring_1_2', x: 1450, y: 680, radius: 42, rotation: 0, collected: false, scoreValue: 250, stabilityBonus: 5 },
      { id: 'ring_1_3', x: 1800, y: 700, radius: 42, rotation: 0, collected: false, scoreValue: 250, stabilityBonus: 5 },
    ],
    routeWaypoints: [
      { x: 250, y: 700 },
      { x: 800, y: 700 },
      { x: 1450, y: 680 },
      { x: 2000, y: 700 },
      { x: 2350, y: 700 },
    ],
  },

  // 2. CADET ASTEROID SLALOM
  {
    id: 'mission_2',
    codeName: 'SEC-02',
    title: 'Asteroid Belt Slalom',
    sector: 'Kalliope Shrapnel Field',
    difficulty: 'cadet',
    description: 'Drifting space rocks and tumbling rogue boulders crowd the shipping corridor. Thread your route through the delivery rings to maintain stability.',
    cargoName: 'Quantum Entanglement Core',
    cargoDescription: 'Delicate crystal lattice that fractures upon severe collision shocks.',
    timeLimit: 65,
    rewardCredits: 250,
    baseScore: 1600,
    unlockRequirement: { type: 'previous_mission', value: 'mission_1' },
    worldWidth: 3200,
    worldHeight: 1800,
    startPos: { x: 300, y: 900, angle: 0 },
    landingPad: {
      x: 2900,
      y: 900,
      width: 140,
      height: 140,
      targetAngle: 0,
      safeSpeedMax: 2.1,
    },
    asteroids: [
      // Static cluster
      { id: 'ast_2_1', type: 'asteroid_static', x: 700, y: 650, radius: 60, rotation: 0.2, rotationSpeed: 0.004, vertices: generateAsteroidVertices(60) },
      { id: 'ast_2_2', type: 'asteroid_static', x: 750, y: 1150, radius: 65, rotation: 0.9, rotationSpeed: -0.003, vertices: generateAsteroidVertices(65) },
      { id: 'ast_2_3', type: 'asteroid_static', x: 1200, y: 880, radius: 75, rotation: 1.4, rotationSpeed: 0.005, vertices: generateAsteroidVertices(75) },
      { id: 'ast_2_4', type: 'asteroid_static', x: 1600, y: 600, radius: 70, rotation: 0.6, rotationSpeed: -0.005, vertices: generateAsteroidVertices(70) },
      { id: 'ast_2_5', type: 'asteroid_static', x: 1650, y: 1200, radius: 80, rotation: 2.3, rotationSpeed: 0.004, vertices: generateAsteroidVertices(80) },
      { id: 'ast_2_6', type: 'asteroid_static', x: 2100, y: 850, radius: 85, rotation: 1.7, rotationSpeed: -0.003, vertices: generateAsteroidVertices(85) },
      { id: 'ast_2_7', type: 'asteroid_static', x: 2550, y: 650, radius: 60, rotation: 0.3, rotationSpeed: 0.005, vertices: generateAsteroidVertices(60) },
      { id: 'ast_2_8', type: 'asteroid_static', x: 2600, y: 1150, radius: 60, rotation: 1.1, rotationSpeed: -0.004, vertices: generateAsteroidVertices(60) },
      // Moving patrol asteroids
      {
        id: 'ast_2_m1',
        type: 'asteroid_moving',
        x: 1000,
        y: 700,
        radius: 45,
        vx: 0,
        vy: 1.6,
        minY: 600,
        maxY: 1200,
        rotation: 0,
        rotationSpeed: 0.02,
        vertices: generateAsteroidVertices(45),
      },
      {
        id: 'ast_2_m2',
        type: 'asteroid_moving',
        x: 1850,
        y: 1100,
        radius: 48,
        vx: 0,
        vy: -1.8,
        minY: 650,
        maxY: 1250,
        rotation: 0,
        rotationSpeed: -0.02,
        vertices: generateAsteroidVertices(48),
      },
      {
        id: 'ast_2_m3',
        type: 'asteroid_moving',
        x: 2350,
        y: 750,
        radius: 50,
        vx: 0,
        vy: 1.5,
        minY: 650,
        maxY: 1150,
        rotation: 0,
        rotationSpeed: 0.015,
        vertices: generateAsteroidVertices(50),
      },
    ],
    gravityWells: [],
    lasers: [],
    bonusRings: [
      { id: 'ring_2_1', x: 950, y: 900, radius: 45, rotation: 0, collected: false, scoreValue: 300, stabilityBonus: 8 },
      { id: 'ring_2_2', x: 1450, y: 750, radius: 45, rotation: 0, collected: false, scoreValue: 300, stabilityBonus: 8 },
      { id: 'ring_2_3', x: 1450, y: 1050, radius: 45, rotation: 0, collected: false, scoreValue: 300, stabilityBonus: 8 },
      { id: 'ring_2_4', x: 2350, y: 900, radius: 45, rotation: 0, collected: false, scoreValue: 300, stabilityBonus: 8 },
    ],
    routeWaypoints: [
      { x: 300, y: 900 },
      { x: 950, y: 900 },
      { x: 1450, y: 750 },
      { x: 1900, y: 900 },
      { x: 2400, y: 900 },
      { x: 2900, y: 900 },
    ],
  },

  // 3. SINGULARITY RUN
  {
    id: 'mission_3',
    codeName: 'SEC-03',
    title: 'Singularity Drift',
    sector: 'Dark Nebular Rift',
    difficulty: 'cadet',
    description: 'Active gravitational anomalies warp spacetime along this route. Counter the gravitational pull with boost thrusters before your trajectory collapses into the event horizon.',
    cargoName: 'Plasma Battery Cells',
    cargoDescription: 'Highly volatile energy cells sensitive to gravitational tidal shear.',
    timeLimit: 70,
    rewardCredits: 350,
    baseScore: 2200,
    unlockRequirement: { type: 'previous_mission', value: 'mission_2' },
    worldWidth: 3400,
    worldHeight: 2000,
    startPos: { x: 300, y: 1000, angle: 0 },
    landingPad: {
      x: 3100,
      y: 1000,
      width: 140,
      height: 140,
      targetAngle: 0,
      safeSpeedMax: 2.0,
    },
    asteroids: [
      { id: 'ast_3_1', type: 'asteroid_static', x: 750, y: 700, radius: 60, rotation: 0.1, rotationSpeed: 0.003, vertices: generateAsteroidVertices(60) },
      { id: 'ast_3_2', type: 'asteroid_static', x: 750, y: 1300, radius: 60, rotation: 0.8, rotationSpeed: -0.003, vertices: generateAsteroidVertices(60) },
      { id: 'ast_3_3', type: 'asteroid_static', x: 1950, y: 700, radius: 70, rotation: 1.5, rotationSpeed: 0.004, vertices: generateAsteroidVertices(70) },
      { id: 'ast_3_4', type: 'asteroid_static', x: 1950, y: 1300, radius: 70, rotation: 2.1, rotationSpeed: -0.004, vertices: generateAsteroidVertices(70) },
      { id: 'ast_3_5', type: 'asteroid_static', x: 2700, y: 850, radius: 55, rotation: 0.5, rotationSpeed: 0.005, vertices: generateAsteroidVertices(55) },
      { id: 'ast_3_6', type: 'asteroid_static', x: 2700, y: 1150, radius: 55, rotation: 1.9, rotationSpeed: -0.005, vertices: generateAsteroidVertices(55) },
    ],
    gravityWells: [
      {
        id: 'grav_3_1',
        type: 'gravity_well',
        x: 1350,
        y: 1000,
        radius: 35,
        influenceRadius: 360,
        pullStrength: 0.38,
        rotation: 0,
      },
      {
        id: 'grav_3_2',
        type: 'gravity_well',
        x: 2350,
        y: 800,
        radius: 30,
        influenceRadius: 320,
        pullStrength: 0.35,
        rotation: 0,
      },
      {
        id: 'grav_3_3',
        type: 'gravity_well',
        x: 2350,
        y: 1250,
        radius: 30,
        influenceRadius: 320,
        pullStrength: 0.35,
        rotation: 0,
      },
    ],
    lasers: [],
    bonusRings: [
      { id: 'ring_3_1', x: 900, y: 1000, radius: 45, rotation: 0, collected: false, scoreValue: 350, stabilityBonus: 10 },
      { id: 'ring_3_2', x: 1350, y: 680, radius: 45, rotation: 0, collected: false, scoreValue: 400, stabilityBonus: 10 },
      { id: 'ring_3_3', x: 1350, y: 1320, radius: 45, rotation: 0, collected: false, scoreValue: 400, stabilityBonus: 10 },
      { id: 'ring_3_4', x: 2350, y: 1020, radius: 45, rotation: 0, collected: false, scoreValue: 450, stabilityBonus: 10 },
      { id: 'ring_3_5', x: 2850, y: 1000, radius: 45, rotation: 0, collected: false, scoreValue: 350, stabilityBonus: 10 },
    ],
    routeWaypoints: [
      { x: 300, y: 1000 },
      { x: 900, y: 1000 },
      { x: 1350, y: 680 },
      { x: 1850, y: 1000 },
      { x: 2350, y: 1020 },
      { x: 3100, y: 1000 },
    ],
  },

  // 4. NEON LASER GRIDLOCK
  {
    id: 'mission_4',
    codeName: 'SEC-04',
    title: 'Neon Gridlock Express',
    sector: 'Neo-Tokyo Orbit Way',
    difficulty: 'expert',
    description: 'High-density orbital perimeter protected by automated perimeter lasers. Time your flight windows precisely to slip through cycling energy barriers.',
    cargoName: 'Synthetic Neuro-Chips',
    cargoDescription: 'Ultra-pure bio-neural matrix. Vulnerable to thermal laser radiation.',
    timeLimit: 75,
    rewardCredits: 500,
    baseScore: 2800,
    unlockRequirement: { type: 'previous_mission', value: 'mission_3' },
    worldWidth: 3600,
    worldHeight: 1800,
    startPos: { x: 300, y: 900, angle: 0 },
    landingPad: {
      x: 3300,
      y: 900,
      width: 140,
      height: 140,
      targetAngle: 0,
      safeSpeedMax: 1.9,
    },
    asteroids: [
      { id: 'ast_4_1', type: 'asteroid_static', x: 600, y: 550, radius: 55, rotation: 0, rotationSpeed: 0.003, vertices: generateAsteroidVertices(55) },
      { id: 'ast_4_2', type: 'asteroid_static', x: 600, y: 1250, radius: 55, rotation: 0, rotationSpeed: -0.003, vertices: generateAsteroidVertices(55) },
      { id: 'ast_4_3', type: 'asteroid_static', x: 1550, y: 900, radius: 75, rotation: 0.5, rotationSpeed: 0.004, vertices: generateAsteroidVertices(75) },
      { id: 'ast_4_4', type: 'asteroid_static', x: 2500, y: 550, radius: 60, rotation: 1.2, rotationSpeed: -0.004, vertices: generateAsteroidVertices(60) },
      { id: 'ast_4_5', type: 'asteroid_static', x: 2500, y: 1250, radius: 60, rotation: 2.1, rotationSpeed: 0.004, vertices: generateAsteroidVertices(60) },
    ],
    gravityWells: [],
    lasers: [
      // Laser Gate 1
      { id: 'laser_4_1', type: 'laser_barrier', x1: 1050, y1: 500, x2: 1050, y2: 1300, cycleDuration: 3.2, activeRatio: 0.55, cycleOffset: 0 },
      // Laser Gate 2 Upper & Lower split
      { id: 'laser_4_2', type: 'laser_barrier', x1: 2000, y1: 450, x2: 2000, y2: 850, cycleDuration: 2.8, activeRatio: 0.5, cycleOffset: 1.2 },
      { id: 'laser_4_3', type: 'laser_barrier', x1: 2000, y1: 950, x2: 2000, y2: 1350, cycleDuration: 2.8, activeRatio: 0.5, cycleOffset: 0 },
      // Laser Gate 3 Final Gate
      { id: 'laser_4_4', type: 'laser_barrier', x1: 2900, y1: 550, x2: 2900, y2: 1250, cycleDuration: 3.0, activeRatio: 0.5, cycleOffset: 1.5 },
    ],
    bonusRings: [
      { id: 'ring_4_1', x: 800, y: 900, radius: 45, rotation: 0, collected: false, scoreValue: 350, stabilityBonus: 8 },
      { id: 'ring_4_2', x: 1550, y: 650, radius: 45, rotation: 0, collected: false, scoreValue: 400, stabilityBonus: 8 },
      { id: 'ring_4_3', x: 1550, y: 1150, radius: 45, rotation: 0, collected: false, scoreValue: 400, stabilityBonus: 8 },
      { id: 'ring_4_4', x: 2450, y: 900, radius: 45, rotation: 0, collected: false, scoreValue: 450, stabilityBonus: 8 },
      { id: 'ring_4_5', x: 3100, y: 900, radius: 45, rotation: 0, collected: false, scoreValue: 400, stabilityBonus: 8 },
    ],
    routeWaypoints: [
      { x: 300, y: 900 },
      { x: 1050, y: 900 },
      { x: 1550, y: 650 },
      { x: 2000, y: 900 },
      { x: 2900, y: 900 },
      { x: 3300, y: 900 },
    ],
  },

  // 5. PLASMA CANYON
  {
    id: 'mission_5',
    codeName: 'SEC-05',
    title: 'Plasma Trench Infiltration',
    sector: 'Tartarus Rift Trench',
    difficulty: 'expert',
    description: 'A treacherous winding canyon passage containing swirling gravitational eddies, drifting barrier asteroids, and intermittent laser tripwires.',
    cargoName: 'Relic Antimatter Matrix',
    cargoDescription: 'Extremely fragile relic container. Even a minor crash breaches containment.',
    timeLimit: 85,
    rewardCredits: 700,
    baseScore: 3500,
    unlockRequirement: { type: 'previous_mission', value: 'mission_4' },
    worldWidth: 4000,
    worldHeight: 2200,
    startPos: { x: 300, y: 600, angle: 0 },
    landingPad: {
      x: 3700,
      y: 1600,
      width: 140,
      height: 140,
      targetAngle: 0,
      safeSpeedMax: 1.8,
    },
    asteroids: [
      // Trench boundary mock
      { id: 'ast_5_1', type: 'asteroid_static', x: 800, y: 350, radius: 80, rotation: 0, rotationSpeed: 0.002, vertices: generateAsteroidVertices(80) },
      { id: 'ast_5_2', type: 'asteroid_static', x: 800, y: 950, radius: 80, rotation: 0, rotationSpeed: -0.002, vertices: generateAsteroidVertices(80) },
      { id: 'ast_5_3', type: 'asteroid_static', x: 1600, y: 800, radius: 90, rotation: 1, rotationSpeed: 0.003, vertices: generateAsteroidVertices(90) },
      { id: 'ast_5_4', type: 'asteroid_static', x: 1600, y: 1500, radius: 90, rotation: 2, rotationSpeed: -0.003, vertices: generateAsteroidVertices(90) },
      { id: 'ast_5_5', type: 'asteroid_static', x: 2600, y: 1100, radius: 95, rotation: 0.5, rotationSpeed: 0.002, vertices: generateAsteroidVertices(95) },
      { id: 'ast_5_6', type: 'asteroid_static', x: 2600, y: 1900, radius: 95, rotation: 1.5, rotationSpeed: -0.002, vertices: generateAsteroidVertices(95) },
      // Patrol asteroids
      {
        id: 'ast_5_m1',
        type: 'asteroid_moving',
        x: 1200,
        y: 600,
        radius: 45,
        vx: 0,
        vy: 2.0,
        minY: 450,
        maxY: 850,
        rotation: 0,
        rotationSpeed: 0.02,
        vertices: generateAsteroidVertices(45),
      },
      {
        id: 'ast_5_m2',
        type: 'asteroid_moving',
        x: 2100,
        y: 1100,
        radius: 50,
        vx: 0,
        vy: -2.0,
        minY: 900,
        maxY: 1350,
        rotation: 0,
        rotationSpeed: -0.02,
        vertices: generateAsteroidVertices(50),
      },
      {
        id: 'ast_5_m3',
        type: 'asteroid_moving',
        x: 3100,
        y: 1500,
        radius: 50,
        vx: 0,
        vy: 1.8,
        minY: 1300,
        maxY: 1800,
        rotation: 0,
        rotationSpeed: 0.015,
        vertices: generateAsteroidVertices(50),
      },
    ],
    gravityWells: [
      {
        id: 'grav_5_1',
        type: 'gravity_well',
        x: 1900,
        y: 700,
        radius: 35,
        influenceRadius: 340,
        pullStrength: 0.36,
        rotation: 0,
      },
      {
        id: 'grav_5_2',
        type: 'gravity_well',
        x: 2900,
        y: 1200,
        radius: 35,
        influenceRadius: 340,
        pullStrength: 0.38,
        rotation: 0,
      },
    ],
    lasers: [
      { id: 'laser_5_1', type: 'laser_barrier', x1: 1400, y1: 400, x2: 1400, y2: 1000, cycleDuration: 3.0, activeRatio: 0.5, cycleOffset: 0.5 },
      { id: 'laser_5_2', type: 'laser_barrier', x1: 2400, y1: 900, x2: 2400, y2: 1600, cycleDuration: 3.2, activeRatio: 0.5, cycleOffset: 1.6 },
      { id: 'laser_5_3', type: 'laser_barrier', x1: 3400, y1: 1300, x2: 3400, y2: 1900, cycleDuration: 2.8, activeRatio: 0.5, cycleOffset: 0 },
    ],
    bonusRings: [
      { id: 'ring_5_1', x: 800, y: 650, radius: 45, rotation: 0, collected: false, scoreValue: 400, stabilityBonus: 10 },
      { id: 'ring_5_2', x: 1600, y: 1150, radius: 45, rotation: 0, collected: false, scoreValue: 450, stabilityBonus: 10 },
      { id: 'ring_5_3', x: 2300, y: 1350, radius: 45, rotation: 0, collected: false, scoreValue: 450, stabilityBonus: 10 },
      { id: 'ring_5_4', x: 3100, y: 1600, radius: 45, rotation: 0, collected: false, scoreValue: 500, stabilityBonus: 12 },
      { id: 'ring_5_5', x: 3500, y: 1600, radius: 45, rotation: 0, collected: false, scoreValue: 400, stabilityBonus: 10 },
    ],
    routeWaypoints: [
      { x: 300, y: 600 },
      { x: 800, y: 650 },
      { x: 1600, y: 1150 },
      { x: 2400, y: 1350 },
      { x: 3100, y: 1600 },
      { x: 3700, y: 1600 },
    ],
  },

  // 6. HYPERLANE ODYSSEY (MASTER CHALLENGE)
  {
    id: 'mission_6',
    codeName: 'SEC-06',
    title: 'The Hyperlane Odyssey',
    sector: 'Galactic Core Relay',
    difficulty: 'hyper',
    description: 'The ultimate courier trial across the Galactic Core relay. Supreme speed, spatial anomalies, moving debris storms, and multi-phased laser gauntlets.',
    cargoName: 'Cosmic Singularity Seed',
    cargoDescription: 'Supreme class package. Zero tolerance for high-G impacts. High courier honorarium.',
    timeLimit: 95,
    rewardCredits: 1200,
    baseScore: 5000,
    unlockRequirement: { type: 'previous_mission', value: 'mission_5' },
    worldWidth: 4600,
    worldHeight: 2400,
    startPos: { x: 300, y: 1200, angle: 0 },
    landingPad: {
      x: 4300,
      y: 1200,
      width: 145,
      height: 145,
      targetAngle: 0,
      safeSpeedMax: 1.8,
    },
    asteroids: [
      { id: 'ast_6_1', type: 'asteroid_static', x: 700, y: 900, radius: 70, rotation: 0, rotationSpeed: 0.003, vertices: generateAsteroidVertices(70) },
      { id: 'ast_6_2', type: 'asteroid_static', x: 700, y: 1500, radius: 70, rotation: 0, rotationSpeed: -0.003, vertices: generateAsteroidVertices(70) },
      { id: 'ast_6_3', type: 'asteroid_static', x: 1600, y: 800, radius: 85, rotation: 1, rotationSpeed: 0.004, vertices: generateAsteroidVertices(85) },
      { id: 'ast_6_4', type: 'asteroid_static', x: 1600, y: 1600, radius: 85, rotation: 2, rotationSpeed: -0.004, vertices: generateAsteroidVertices(85) },
      { id: 'ast_6_5', type: 'asteroid_static', x: 2600, y: 750, radius: 95, rotation: 0.5, rotationSpeed: 0.003, vertices: generateAsteroidVertices(95) },
      { id: 'ast_6_6', type: 'asteroid_static', x: 2600, y: 1650, radius: 95, rotation: 1.5, rotationSpeed: -0.003, vertices: generateAsteroidVertices(95) },
      { id: 'ast_6_7', type: 'asteroid_static', x: 3600, y: 950, radius: 80, rotation: 0.8, rotationSpeed: 0.004, vertices: generateAsteroidVertices(80) },
      { id: 'ast_6_8', type: 'asteroid_static', x: 3600, y: 1450, radius: 80, rotation: 2.2, rotationSpeed: -0.004, vertices: generateAsteroidVertices(80) },
      // Moving interceptor asteroids
      { id: 'ast_6_m1', type: 'asteroid_moving', x: 1150, y: 1000, radius: 52, vx: 0, vy: 2.2, minY: 800, maxY: 1500, rotation: 0, rotationSpeed: 0.02, vertices: generateAsteroidVertices(52) },
      { id: 'ast_6_m2', type: 'asteroid_moving', x: 2150, y: 1350, radius: 54, vx: 0, vy: -2.4, minY: 850, maxY: 1550, rotation: 0, rotationSpeed: -0.02, vertices: generateAsteroidVertices(54) },
      { id: 'ast_6_m3', type: 'asteroid_moving', x: 3150, y: 950, radius: 55, vx: 0, vy: 2.2, minY: 800, maxY: 1600, rotation: 0, rotationSpeed: 0.02, vertices: generateAsteroidVertices(55) },
    ],
    gravityWells: [
      { id: 'grav_6_1', type: 'gravity_well', x: 1400, y: 1200, radius: 36, influenceRadius: 360, pullStrength: 0.4, rotation: 0 },
      { id: 'grav_6_2', type: 'gravity_well', x: 2800, y: 1200, radius: 38, influenceRadius: 380, pullStrength: 0.42, rotation: 0 },
    ],
    lasers: [
      { id: 'laser_6_1', type: 'laser_barrier', x1: 900, y1: 700, x2: 900, y2: 1700, cycleDuration: 3.2, activeRatio: 0.5, cycleOffset: 0 },
      { id: 'laser_6_2', type: 'laser_barrier', x1: 2400, y1: 650, x2: 2400, y2: 1200, cycleDuration: 2.8, activeRatio: 0.45, cycleOffset: 1.0 },
      { id: 'laser_6_3', type: 'laser_barrier', x1: 2400, y1: 1300, x2: 2400, y2: 1800, cycleDuration: 2.8, activeRatio: 0.45, cycleOffset: 0 },
      { id: 'laser_6_4', type: 'laser_barrier', x1: 3800, y1: 800, x2: 3800, y2: 1600, cycleDuration: 3.0, activeRatio: 0.5, cycleOffset: 1.5 },
    ],
    bonusRings: [
      { id: 'ring_6_1', x: 700, y: 1200, radius: 46, rotation: 0, collected: false, scoreValue: 500, stabilityBonus: 10 },
      { id: 'ring_6_2', x: 1400, y: 880, radius: 46, rotation: 0, collected: false, scoreValue: 600, stabilityBonus: 12 },
      { id: 'ring_6_3', x: 1900, y: 1200, radius: 46, rotation: 0, collected: false, scoreValue: 500, stabilityBonus: 10 },
      { id: 'ring_6_4', x: 2800, y: 1550, radius: 46, rotation: 0, collected: false, scoreValue: 600, stabilityBonus: 12 },
      { id: 'ring_6_5', x: 3350, y: 1200, radius: 46, rotation: 0, collected: false, scoreValue: 500, stabilityBonus: 10 },
      { id: 'ring_6_6', x: 4050, y: 1200, radius: 46, rotation: 0, collected: false, scoreValue: 600, stabilityBonus: 15 },
    ],
    routeWaypoints: [
      { x: 300, y: 1200 },
      { x: 700, y: 1200 },
      { x: 1400, y: 880 },
      { x: 2100, y: 1200 },
      { x: 2800, y: 1550 },
      { x: 3500, y: 1200 },
      { x: 4300, y: 1200 },
    ],
  },
];

export const CONTRACTS: Contract[] = [
  // 1. Hyperion Bio-Synthetics
  {
    id: 'contract_1',
    contractCode: 'BNTY-091',
    client: {
      name: 'Hyperion Bio-Synthetics',
      faction: 'Megacorp Consortium',
      badgeColor: '#00f0ff',
      reputationBadge: 'TIER-1 CORPORATE',
    },
    title: 'Operation Chiron: Neural Lattice',
    tagline: 'Covert Deep-Space Bio-Transport',
    briefing: 'A fragile synthetic neural lattice must be transported through an uncharted asteroid pocket. High acceleration shifts and sudden impacts will destabilize the cold-storage containment.',
    cargo: {
      name: 'Cryo-Neural Bio-Lattice',
      type: 'BIOHAZARD',
      fragility: 'VOLATILE',
      hazardNote: 'Extreme shock sensitivity. Maintain steady velocity through asteroid pockets.',
    },
    specialHazard: 'Clustered rotating asteroid choke-points with narrow bypass corridors.',
    riskLevel: 'STANDARD',
    rewardCredits: 750,
    rewardXp: 450,
    mission: {
      id: 'contract_mission_1',
      codeName: 'BNTY-091',
      title: 'Neural Lattice Run',
      sector: 'Hyperion Covert Zone',
      difficulty: 'cadet',
      description: 'Pilot through the uncharted Asteroid pocket and deliver the Cryo-Neural Lattice to Research Facility Chiron.',
      cargoName: 'Cryo-Neural Bio-Lattice',
      cargoDescription: 'Volatile biological synthetic consciousness matrix.',
      timeLimit: 55,
      rewardCredits: 750,
      baseScore: 1600,
      unlockRequirement: { type: 'default' },
      worldWidth: 3000,
      worldHeight: 1600,
      startPos: { x: 250, y: 800, angle: 0 },
      landingPad: {
        x: 2750,
        y: 800,
        width: 140,
        height: 140,
        targetAngle: 0,
        safeSpeedMax: 2.2,
      },
      asteroids: [
        { id: 'c1_ast1', type: 'asteroid_static', x: 750, y: 700, radius: 65, rotation: 0.2, rotationSpeed: 0.004, vertices: generateAsteroidVertices(65) },
        { id: 'c1_ast2', type: 'asteroid_static', x: 800, y: 1050, radius: 55, rotation: 1.1, rotationSpeed: -0.005, vertices: generateAsteroidVertices(55) },
        { id: 'c1_ast3', type: 'asteroid_moving', x: 1300, y: 600, radius: 48, vx: 0, vy: 1.5, minY: 400, maxY: 1200, rotation: 0.4, rotationSpeed: 0.012, vertices: generateAsteroidVertices(48) },
        { id: 'c1_ast4', type: 'asteroid_moving', x: 1750, y: 1100, radius: 50, vx: 0, vy: -1.6, minY: 450, maxY: 1250, rotation: 2.1, rotationSpeed: -0.01, vertices: generateAsteroidVertices(50) },
        { id: 'c1_ast5', type: 'asteroid_static', x: 2200, y: 650, radius: 60, rotation: 0.8, rotationSpeed: 0.003, vertices: generateAsteroidVertices(60) },
        { id: 'c1_ast6', type: 'asteroid_static', x: 2250, y: 1000, radius: 58, rotation: 2.5, rotationSpeed: -0.004, vertices: generateAsteroidVertices(58) },
      ],
      gravityWells: [],
      lasers: [],
      bonusRings: [
        { id: 'c1_ring1', x: 600, y: 800, radius: 42, rotation: 0, collected: false, scoreValue: 350, stabilityBonus: 10 },
        { id: 'c1_ring2', x: 1300, y: 800, radius: 42, rotation: 0, collected: false, scoreValue: 400, stabilityBonus: 12 },
        { id: 'c1_ring3', x: 1750, y: 800, radius: 42, rotation: 0, collected: false, scoreValue: 400, stabilityBonus: 12 },
        { id: 'c1_ring4', x: 2450, y: 800, radius: 42, rotation: 0, collected: false, scoreValue: 450, stabilityBonus: 15 },
      ],
      routeWaypoints: [
        { x: 250, y: 800 },
        { x: 1000, y: 800 },
        { x: 1500, y: 800 },
        { x: 2000, y: 800 },
        { x: 2750, y: 800 },
      ],
    },
  },

  // 2. Driftwood Syndicate
  {
    id: 'contract_2',
    contractCode: 'BNTY-142',
    client: {
      name: 'Driftwood Shadow Syndicate',
      faction: 'Smuggler Enclave',
      badgeColor: '#ec4899',
      reputationBadge: 'BLACK MARKET ELITE',
    },
    title: 'The Slipstream Interdiction',
    tagline: 'Perimeter Laser Grid Penetration',
    briefing: 'A high-level corporate military cipher key must breach the automated defense perimeter. Laser barriers pulse in overlapping intervals. Timing thruster bursts is vital.',
    cargo: {
      name: 'Decrypted Syndicate Cipher Core',
      type: 'QUANTUM',
      fragility: 'DELICATE',
      hazardNote: 'Any contact with defense laser beams causes critical system corruption.',
    },
    specialHazard: 'High-frequency pulsing defense laser barriers guarding key transit gates.',
    riskLevel: 'ELEVATED',
    rewardCredits: 1100,
    rewardXp: 700,
    mission: {
      id: 'contract_mission_2',
      codeName: 'BNTY-142',
      title: 'Perimeter Laser Run',
      sector: 'Driftwood Perimeter Grid',
      difficulty: 'expert',
      description: 'Navigate the synchronized laser gate corridor and deliver the Cipher Core to the syndicate hideout.',
      cargoName: 'Syndicate Cipher Core',
      cargoDescription: 'Encrypted military security bypass key.',
      timeLimit: 52,
      rewardCredits: 1100,
      baseScore: 2200,
      unlockRequirement: { type: 'default' },
      worldWidth: 3200,
      worldHeight: 1600,
      startPos: { x: 250, y: 800, angle: 0 },
      landingPad: {
        x: 2950,
        y: 800,
        width: 135,
        height: 135,
        targetAngle: 0,
        safeSpeedMax: 2.1,
      },
      asteroids: [
        { id: 'c2_ast1', type: 'asteroid_static', x: 800, y: 400, radius: 55, rotation: 0.5, rotationSpeed: 0.003, vertices: generateAsteroidVertices(55) },
        { id: 'c2_ast2', type: 'asteroid_static', x: 800, y: 1200, radius: 55, rotation: 1.2, rotationSpeed: -0.003, vertices: generateAsteroidVertices(55) },
        { id: 'c2_ast3', type: 'asteroid_static', x: 1800, y: 450, radius: 60, rotation: 2.1, rotationSpeed: 0.004, vertices: generateAsteroidVertices(60) },
        { id: 'c2_ast4', type: 'asteroid_static', x: 1800, y: 1150, radius: 60, rotation: 0.9, rotationSpeed: -0.004, vertices: generateAsteroidVertices(60) },
      ],
      gravityWells: [],
      lasers: [
        { id: 'c2_las1', type: 'laser_barrier', x1: 1100, y1: 500, x2: 1100, y2: 1100, cycleDuration: 3.0, activeRatio: 0.45, cycleOffset: 0 },
        { id: 'c2_las2', type: 'laser_barrier', x1: 1600, y1: 450, x2: 1600, y2: 1150, cycleDuration: 2.6, activeRatio: 0.45, cycleOffset: 1.3 },
        { id: 'c2_las3', type: 'laser_barrier', x1: 2200, y1: 500, x2: 2200, y2: 1100, cycleDuration: 2.8, activeRatio: 0.5, cycleOffset: 0.6 },
      ],
      bonusRings: [
        { id: 'c2_ring1', x: 650, y: 800, radius: 44, rotation: 0, collected: false, scoreValue: 400, stabilityBonus: 10 },
        { id: 'c2_ring2', x: 1350, y: 800, radius: 44, rotation: 0, collected: false, scoreValue: 500, stabilityBonus: 12 },
        { id: 'c2_ring3', x: 1900, y: 800, radius: 44, rotation: 0, collected: false, scoreValue: 500, stabilityBonus: 12 },
        { id: 'c2_ring4', x: 2600, y: 800, radius: 44, rotation: 0, collected: false, scoreValue: 600, stabilityBonus: 15 },
      ],
      routeWaypoints: [
        { x: 250, y: 800 },
        { x: 800, y: 800 },
        { x: 1350, y: 800 },
        { x: 1900, y: 800 },
        { x: 2600, y: 800 },
        { x: 2950, y: 800 },
      ],
    },
  },

  // 3. Sol Forge Directorate
  {
    id: 'contract_3',
    contractCode: 'BNTY-220',
    client: {
      name: 'Sol Forge Directorate',
      faction: 'Helios Energy Cartel',
      badgeColor: '#f59e0b',
      reputationBadge: 'INDUSTRIAL OVERSEER',
    },
    title: 'Event Horizon Siphon',
    tagline: 'Singularity Grav-Tether Transit',
    briefing: 'Deliver supercritical plasma isotope flasks past the gravitational distortion of an artificial micro-singularity. Counter-steer against gravitational drift.',
    cargo: {
      name: 'Supercritical Plasma Isotopes',
      type: 'VOLATILE',
      fragility: 'VOLATILE',
      hazardNote: 'Gravitational distortion induces high-speed drift and rotational inertia.',
    },
    specialHazard: 'High-density micro gravity well pulling vessels into the core vortex.',
    riskLevel: 'CRITICAL',
    rewardCredits: 1500,
    rewardXp: 950,
    mission: {
      id: 'contract_mission_3',
      codeName: 'BNTY-220',
      title: 'Singularity Slalom',
      sector: 'Helios Magnetic Foundry',
      difficulty: 'expert',
      description: 'Slalom safely around the singularity gravity well and land at the Plasma Refinery.',
      cargoName: 'Supercritical Plasma Isotopes',
      cargoDescription: 'Ultra-pure plasma fuel canisters.',
      timeLimit: 58,
      rewardCredits: 1500,
      baseScore: 2800,
      unlockRequirement: { type: 'default' },
      worldWidth: 3400,
      worldHeight: 1800,
      startPos: { x: 250, y: 900, angle: 0 },
      landingPad: {
        x: 3100,
        y: 900,
        width: 140,
        height: 140,
        targetAngle: 0,
        safeSpeedMax: 2.0,
      },
      asteroids: [
        { id: 'c3_ast1', type: 'asteroid_static', x: 900, y: 550, radius: 58, rotation: 0.6, rotationSpeed: 0.003, vertices: generateAsteroidVertices(58) },
        { id: 'c3_ast2', type: 'asteroid_static', x: 900, y: 1250, radius: 58, rotation: 2.0, rotationSpeed: -0.004, vertices: generateAsteroidVertices(58) },
        { id: 'c3_ast3', type: 'asteroid_static', x: 2300, y: 550, radius: 62, rotation: 1.4, rotationSpeed: 0.003, vertices: generateAsteroidVertices(62) },
        { id: 'c3_ast4', type: 'asteroid_static', x: 2300, y: 1250, radius: 62, rotation: 0.3, rotationSpeed: -0.003, vertices: generateAsteroidVertices(62) },
      ],
      gravityWells: [
        {
          id: 'c3_gw1',
          type: 'gravity_well',
          x: 1600,
          y: 900,
          radius: 55,
          influenceRadius: 420,
          eventHorizonRadius: 55,
          pullStrength: 3.6,
          pulseFrequency: 1.0,
        },
      ],
      lasers: [
        { id: 'c3_las1', type: 'laser_barrier', x1: 2550, y1: 650, x2: 2550, y2: 1150, cycleDuration: 2.8, activeRatio: 0.45, cycleOffset: 0.5 },
      ],
      bonusRings: [
        { id: 'c3_ring1', x: 750, y: 900, radius: 46, rotation: 0, collected: false, scoreValue: 450, stabilityBonus: 10 },
        { id: 'c3_ring2', x: 1600, y: 540, radius: 46, rotation: 0, collected: false, scoreValue: 650, stabilityBonus: 15 },
        { id: 'c3_ring3', x: 1600, y: 1260, radius: 46, rotation: 0, collected: false, scoreValue: 650, stabilityBonus: 15 },
        { id: 'c3_ring4', x: 2800, y: 900, radius: 46, rotation: 0, collected: false, scoreValue: 500, stabilityBonus: 12 },
      ],
      routeWaypoints: [
        { x: 250, y: 900 },
        { x: 1000, y: 900 },
        { x: 1600, y: 600 },
        { x: 2200, y: 900 },
        { x: 3100, y: 900 },
      ],
    },
  },

  // 4. Ghost Fleet Alliance
  {
    id: 'contract_4',
    contractCode: 'BNTY-390',
    client: {
      name: 'Ghost Fleet Alliance',
      faction: 'Deep Void Vanguard',
      badgeColor: '#a855f7',
      reputationBadge: 'LEGENDARY BOUNTY',
    },
    title: 'Obsidian Labyrinth Run',
    tagline: 'Extreme Multi-Hazard Gauntlet',
    briefing: 'The highest tier bounty on the terminal. Deliver an ancient proto-matter hyperdrive core through an alien defense matrix combining dual lasers, moving asteroids, and gravitational turbulence.',
    cargo: {
      name: 'Proto-Matter Hyperdrive Core',
      type: 'QUANTUM',
      fragility: 'QUANTUM',
      hazardNote: 'Zero room for error. Unstable dimensional containment.',
    },
    specialHazard: 'Simultaneous laser grids, moving asteroids, and gravity anomaly.',
    riskLevel: 'EXTREME',
    rewardCredits: 2200,
    rewardXp: 1500,
    mission: {
      id: 'contract_mission_4',
      codeName: 'BNTY-390',
      title: 'Obsidian Citadel Run',
      sector: 'Obsidian Void Nexus',
      difficulty: 'hyper',
      description: 'Survive the multi-hazard alien defense matrix and dock at the Ghost Fleet flagship.',
      cargoName: 'Proto-Matter Hyperdrive Core',
      cargoDescription: 'Pristine experimental hyperdrive core.',
      timeLimit: 62,
      rewardCredits: 2200,
      baseScore: 3500,
      unlockRequirement: { type: 'default' },
      worldWidth: 3800,
      worldHeight: 1800,
      startPos: { x: 250, y: 900, angle: 0 },
      landingPad: {
        x: 3550,
        y: 900,
        width: 145,
        height: 145,
        targetAngle: 0,
        safeSpeedMax: 2.0,
      },
      asteroids: [
        { id: 'c4_ast1', type: 'asteroid_static', x: 800, y: 550, radius: 55, rotation: 0.3, rotationSpeed: 0.003, vertices: generateAsteroidVertices(55) },
        { id: 'c4_ast2', type: 'asteroid_static', x: 800, y: 1250, radius: 55, rotation: 1.8, rotationSpeed: -0.003, vertices: generateAsteroidVertices(55) },
        { id: 'c4_ast3', type: 'asteroid_moving', x: 1550, y: 650, radius: 50, vx: 0, vy: 1.8, minY: 450, maxY: 1350, rotation: 0.7, rotationSpeed: 0.012, vertices: generateAsteroidVertices(50) },
        { id: 'c4_ast4', type: 'asteroid_moving', x: 2750, y: 1150, radius: 52, vx: 0, vy: -1.8, minY: 450, maxY: 1350, rotation: 2.2, rotationSpeed: -0.012, vertices: generateAsteroidVertices(52) },
      ],
      gravityWells: [
        {
          id: 'c4_gw1',
          type: 'gravity_well',
          x: 2150,
          y: 900,
          radius: 52,
          influenceRadius: 400,
          eventHorizonRadius: 52,
          pullStrength: 3.8,
          pulseFrequency: 1.2,
        },
      ],
      lasers: [
        { id: 'c4_las1', type: 'laser_barrier', x1: 1150, y1: 550, x2: 1150, y2: 1250, cycleDuration: 3.0, activeRatio: 0.45, cycleOffset: 0 },
        { id: 'c4_las2', type: 'laser_barrier', x1: 3100, y1: 550, x2: 3100, y2: 1250, cycleDuration: 2.7, activeRatio: 0.45, cycleOffset: 1.2 },
      ],
      bonusRings: [
        { id: 'c4_ring1', x: 600, y: 900, radius: 45, rotation: 0, collected: false, scoreValue: 500, stabilityBonus: 10 },
        { id: 'c4_ring2', x: 1350, y: 900, radius: 45, rotation: 0, collected: false, scoreValue: 600, stabilityBonus: 12 },
        { id: 'c4_ring3', x: 2150, y: 550, radius: 45, rotation: 0, collected: false, scoreValue: 800, stabilityBonus: 15 },
        { id: 'c4_ring4', x: 2150, y: 1250, radius: 45, rotation: 0, collected: false, scoreValue: 800, stabilityBonus: 15 },
        { id: 'c4_ring5', x: 3350, y: 900, radius: 45, rotation: 0, collected: false, scoreValue: 700, stabilityBonus: 12 },
      ],
      routeWaypoints: [
        { x: 250, y: 900 },
        { x: 950, y: 900 },
        { x: 1750, y: 900 },
        { x: 2150, y: 600 },
        { x: 2550, y: 900 },
        { x: 3550, y: 900 },
      ],
    },
  },
];

export const DEFAULT_PLAYER_PROFILE: PlayerProfile = {
  callsign: 'COURIER-7',
  totalCredits: 0,
  totalXp: 0,
  currentLevel: 1,
  selectedShipId: 'star_sparrow',
  unlockedShipIds: ['star_sparrow'],
  completedMissionIds: [],
  completedContractIds: [],
  bestScores: {},
  bestTimes: {},
  settings: {
    difficulty: 'courier',
    controlMode: 'laptop',
    fuelDepletion: true,
    mouseControls: true,
    masterVolume: 0.8,
    sfxVolume: 0.85,
    musicVolume: 0.65,
    soundEnabled: true,
    musicEnabled: true,
    controlSensitivity: 1.0,
    assistMode: false,
    showTouchControls: false,
    particlesEnabled: true,
    screenShake: true,
  },
  statistics: {
    missionsAttempted: 0,
    totalGamesPlayed: 0,
    deliveriesCompleted: 0,
    flawlessDeliveries: 0,
    packagesBroken: 0,
    bonusRingsCollected: 0,
    totalDistanceTraveled: 0,
  },
};
